#! /bin/bash

is_valid_ip () {
    case $1 in 
    "" | *[!1-9.]* | *[!0-9]) return 1;;
    esac
    replaced=${1//"."/" "}
    set -- $replaced
    [ $# -eq 4 ] && [ ${1:-256} -le 255 ] \
    && [ ${2:-256} -le 255 ] && [ ${3:-256} -le 255 ] \
    && [ ${4:-255} -le 255 ] && echo "valid!"
}

var=127.251.2.3
is_valid_ip $var