#! /bin/bash

# echo "Matching file $2 from Pattern $1" 
# while IFS=' ' read -r line || [[ -n "$line" ]]; do
#     # line=$(echo $line | od -xc)
#     index=$(echo $line | awk '{print $2}')
#     value=$(echo $line | awk '{print $1}')
#     # index=$line
#     # echo $index
#     # echo $index
#     # echo $line
#     index=${index%%[[:space:]]}
#     # echo $line
#     grep ";davisWiki\/${index};" $2 >> idx
#     echo $value
# done < "$1"

while IFS=';' read -r index filename length || [[ -n "$index" ]]; do
    # echo $line
    prefix="davisWiki/"
    name=${filename#"$prefix"}
    line=$(grep ";$name" $2)
    newline="$index;${line%%[[:space:]]}"
    echo $newline >> result
done < "$1"
