#! /bin/bash


files=$(ls)
while true
do
	printf "enter a file name \n"
    echo $files 
	read var
    if [ -f $var ]
    then 
        echo file $var exists
        break
    elif [ -d $var ]
    then 
        echo dir $var exists
        break
    else 
        echo $var does not exist in this dir
        continue
    fi
done