#! /bin/bash

while true
do
	printf "enter a number between 20 to 30 \n"
	read var
	if [ $var -lt 20 ]
	then
		printf "%d is too small\n" "$var"
		continue
	elif [ $var -gt 30 ]
	then 
		printf "%d is too large\n" "$var"
		continue
	else
		printf "%d is good\n" "$var"
		break
	fi
done
