#! /bin/bash

optstr=f:v
verbose=0
filename=

while getopts $optstr opt
do
    case $opt in 
        f) filename=$OPTARG ;;
        v) verbose=$(( $verbose + 1 ))
            echo verbose is turned on  ;;
        *) exit 1 ;;
    esac
done


if [ -z "$filename" ]
then
    if [ $verbose -gt 0 ]
    then 
        echo "no file name entered"!
    fi
        exit 1
else 
    if [ $verbose -gt 0 ]
    then 
        echo "you chose $filename"
    fi
fi

if [ -f "$filename" ]
then
    if [ $verbose -gt 0 ]
    then 
        echo "$filename exists!"
    fi
else 
    if [ $verbose -gt 0 ]
    then 
        echo "$filename does not exist!"
    fi
    exit 2
fi

if [ $verbose -gt 0 ]
then 
    echo Number of arguments is $#
fi

